apiVersion: v1
kind: LimitRange
metadata:
  name: employee-prod-limits
  namespace: employee-prod
spec:
  limits:
  - type: Container

    # Default values applied if omitted
    default:
      cpu: "500m"
      memory: "512Mi"

    # Default requests
    defaultRequest:
      cpu: "250m"
      memory: "256Mi"

    # Maximum allowed
    max:
      cpu: "2"
      memory: "2Gi"

    # Minimum allowed
    min:
      cpu: "100m"
      memory: "128Mi"
