apiVersion: v1
kind: ResourceQuota
metadata:
  name: employee-prod-quota
  namespace: employee-prod
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi

    limits.cpu: "8"
    limits.memory: 16Gi

    pods: "50"

    persistentvolumeclaims: "10"

    requests.storage: 100Gi

    services: "10"

    secrets: "30"

    configmaps: "20"

    count/deployments.apps: "20"

    count/jobs.batch: "10"

    count/cronjobs.batch: "5"

    count/ingresses.networking.k8s.io: "5"
