name: CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: enterprise-idp-lab-eks

  BACKEND_REPOSITORY: python-crud-frontend
  FRONTEND_REPOSITORY: python-crud-frontend

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Backend
      run: |
        docker build \
        -t $BACKEND_REPOSITORY:${{ github.sha }} \
        backend/

    - name: Tag Backend
      run: |
        docker tag \
        $BACKEND_REPOSITORY:${{ github.sha }} \
        ${{ steps.login-ecr.outputs.registry }}/$BACKEND_REPOSITORY:${{ github.sha }}

        docker tag \
        $BACKEND_REPOSITORY:${{ github.sha }} \
        ${{ steps.login-ecr.outputs.registry }}/$BACKEND_REPOSITORY:latest

    - name: Push Backend
      run: |
        docker push \
        ${{ steps.login-ecr.outputs.registry }}/$BACKEND_REPOSITORY:${{ github.sha }}

        docker push \
        ${{ steps.login-ecr.outputs.registry }}/$BACKEND_REPOSITORY:latest

    - name: Build Frontend
      run: |
        docker build \
        -t $FRONTEND_REPOSITORY:${{ github.sha }} \
        frontend/

    - name: Tag Frontend
      run: |
        docker tag \
        $FRONTEND_REPOSITORY:${{ github.sha }} \
        ${{ steps.login-ecr.outputs.registry }}/$FRONTEND_REPOSITORY:${{ github.sha }}

        docker tag \
        $FRONTEND_REPOSITORY:${{ github.sha }} \
        ${{ steps.login-ecr.outputs.registry }}/$FRONTEND_REPOSITORY:latest

    - name: Push Frontend
      run: |
        docker push \
        ${{ steps.login-ecr.outputs.registry }}/$FRONTEND_REPOSITORY:${{ github.sha }}

        docker push \
        ${{ steps.login-ecr.outputs.registry }}/$FRONTEND_REPOSITORY:latest

    - name: Install kubectl
      uses: azure/setup-kubectl@v4

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig \
        --name $CLUSTER_NAME \
        --region $AWS_REGION

    - name: Update Backend Image
      run: |
        kubectl set image deployment/employee-api \
        employee-api=${{ steps.login-ecr.outputs.registry }}/$BACKEND_REPOSITORY:${{ github.sha }} \
        -n employee-prod

    - name: Update Frontend Image
      run: |
        kubectl set image deployment/employee-ui \
        employee-ui=${{ steps.login-ecr.outputs.registry }}/$FRONTEND_REPOSITORY:${{ github.sha }} \
        -n employee-prod

    - name: Wait for Rollout
      run: |
        kubectl rollout status deployment/employee-api -n employee
        kubectl rollout status deployment/employee-ui -n employee

    - name: Smoke Test
      run: |
        kubectl get pods -n employee
        kubectl get svc -n employee
