name: CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  security-events: write

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: enterprise-idp-lab-eks

  BACKEND_REPOSITORY: python-crud-backend
  FRONTEND_REPOSITORY: python-crud-frontend

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    #################################################
    # AWS LOGIN
    #################################################

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    #################################################
    # BUILD BACKEND
    #################################################

    - name: Build Backend
      run: |
        docker build \
          -t $BACKEND_REPOSITORY:${{ github.sha }} \
          backend/

    #################################################
    # BUILD FRONTEND
    #################################################

    - name: Build Frontend
      run: |
        docker build \
          -t $FRONTEND_REPOSITORY:${{ github.sha }} \
          frontend/

    #################################################
    # HADOLINT
    #################################################

    - name: Scan Backend Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      continue-on-error: true
      with:
        dockerfile: backend/Dockerfile

    - name: Scan Frontend Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      continue-on-error: true
      with:
        dockerfile: frontend/Dockerfile

    #################################################
    # GITLEAKS
    #################################################

    - name: Scan Secrets
      uses: gitleaks/gitleaks-action@v2
      continue-on-error: true

    #################################################
    # SEMGREP
    #################################################

    - name: Semgrep Scan
      uses: returntocorp/semgrep-action@v1
      continue-on-error: true

    #################################################
    # TRIVY BACKEND
    #################################################

    - name: Scan Backend Image
      uses: aquasecurity/trivy-action@v0.36.0
      continue-on-error: true
      with:
        image-ref: python-crud-backend:${{ github.sha }}
        format: table
        exit-code: 0

    #################################################
    # TRIVY FRONTEND
    #################################################

    - name: Scan Frontend Image
      uses: aquasecurity/trivy-action@v0.36.0
      continue-on-error: true
      with:
        image-ref: python-crud-frontend:${{ github.sha }}
        format: table
        exit-code: 0

    #################################################
    # TAG IMAGES
    #################################################

    - name: Tag Backend
      run: |
        docker tag \
        $BACKEND_REPOSITORY:${{ github.sha }} \
        ${{ steps.login-ecr.outputs.registry }}/$BACKEND_REPOSITORY:${{ github.sha }}

        docker tag \
        $BACKEND_REPOSITORY:${{ github.sha }} \
        ${{ steps.login-ecr.outputs.registry }}/$BACKEND_REPOSITORY:latest

    - name: Tag Frontend
      run: |
        docker tag \
        $FRONTEND_REPOSITORY:${{ github.sha }} \
        ${{ steps.login-ecr.outputs.registry }}/$FRONTEND_REPOSITORY:${{ github.sha }}

        docker tag \
        $FRONTEND_REPOSITORY:${{ github.sha }} \
        ${{ steps.login-ecr.outputs.registry }}/$FRONTEND_REPOSITORY:latest

    #################################################
    # PUSH IMAGES
    #################################################

    - name: Push Backend
      run: |
        docker push \
        ${{ steps.login-ecr.outputs.registry }}/$BACKEND_REPOSITORY:${{ github.sha }}

        docker push \
        ${{ steps.login-ecr.outputs.registry }}/$BACKEND_REPOSITORY:latest

    - name: Push Frontend
      run: |
        docker push \
        ${{ steps.login-ecr.outputs.registry }}/$FRONTEND_REPOSITORY:${{ github.sha }}

        docker push \
        ${{ steps.login-ecr.outputs.registry }}/$FRONTEND_REPOSITORY:latest

    #################################################
    # KUBECTL
    #################################################

    - name: Install kubectl
      uses: azure/setup-kubectl@v4

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig \
        --name $CLUSTER_NAME \
        --region $AWS_REGION

    #################################################
    # DEPLOY
    #################################################

    - name: Update Backend
      run: |
        kubectl set image deployment/employee-api \
        employee-api=${{ steps.login-ecr.outputs.registry }}/$BACKEND_REPOSITORY:${{ github.sha }} \
        -n employee-prod

    - name: Update Frontend
      run: |
        kubectl set image deployment/employee-ui \
        employee-ui=${{ steps.login-ecr.outputs.registry }}/$FRONTEND_REPOSITORY:${{ github.sha }} \
        -n employee-prod

    #################################################
    # WAIT
    #################################################

    - name: Wait for Rollout
      run: |
        kubectl rollout status deployment/employee-api -n employee-prod
        kubectl rollout status deployment/employee-ui -n employee-prod

    #################################################
    # SMOKE TEST
    #################################################

    - name: Smoke Test
      run: |
        kubectl get pods -n employee-prod
        kubectl get svc -n employee-prod
        kubectl get ingress -n employee-prod

    #################################################
    # UPLOAD REPORTS
    #################################################

    - name: Upload Security Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: DevSecOps-Reports
        path: .
